language: cpp

compiler: g++

install:
  - sudo apt-get update
  - sudo apt-get install qtdeclarative5-dev qt5-qmake qt5-default qtmultimedia5-dev libqt5multimediawidgets5 libqt5multimedia5-plugins libqt5multimedia5

script:
  - qmake Zeno.pro
  - make 	
