######################################################################
# Automatically generated by qmake (3.0) Mon Feb 26 18:40:41 2018
######################################################################

TEMPLATE = app
TARGET = Zeno
INCLUDEPATH += .

# Input
HEADERS += MyRect.h
SOURCES += main.cpp MyRect.cpp

QT += core gui
QT += widgets