######################################################################
# Automatically generated by qmake (3.0) Tue Feb 27 02:24:35 2018
######################################################################

TEMPLATE = app
TARGET = Zeno
INCLUDEPATH += .

# Input
HEADERS += Board.h button.h Game.h \
    Player.h
SOURCES += Board.cpp button.cpp Game.cpp main.cpp \
    Player.cpp

CONFIG += c++11

QT += core gui
QT += widgets
